fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
      repo: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.0.3'
  symlinks:
    splunkforwarder: "#{source_dir}"
